bootstrap updated
cxxxxxxd/CloudStore pull request #3
Opened 2022-01-13 16:50 UTC by syegod

update all views, add to bootstrap.css class "btn-default"

2022-01-13 21:40 UTC, cxxxxxxd requested changes

2022-01-13 21:40 UTC, changerd commented on CloudStore/Migrations/202201131904109_DataMigration2.cs
> +}
Delete empty migration

2022-01-13 21:40 UTC, changerd commented on CloudStore/Models/News.cs
> +        [Display(Name = "News theme")]
Please change to News subject

2022-01-13 21:40 UTC, changerd commented on CloudStore/Models/News.cs
> +        [Display(Name = "News text")]
Please change to News body

2022-01-13 21:40 UTC, changerd commented on CloudStore/Models/RegisterModel.cs
> +        [Compare("RegisterPassword", ErrorMessage = "Password do not match")]
"Password doesn't match" is right label

2022-01-13 21:40 UTC, changerd commented on CloudStore/Models/StoreContext.cs
> +            StatusProduct sp2 = new StatusProduct { StatusProductName = "Not available" };
Out of stock

2022-01-13 21:40 UTC, changerd commented on CloudStore/Models/StoreContext.cs
> +            TypeDelivery td1 = new TypeDelivery { TypeDeliveryName = "Pickup" };
Pick Up

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateCategory.cshtml
> +    ViewBag.Title = "Creating product category";
Create category

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateCategory.cshtml
> +<h2>Create product category</h2>
The same comment

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateManufacturer.cshtml
> +    ViewBag.Title = "Creating manufacturer";
Create

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateProduct.cshtml
> +            @Html.Label("In stock", htmlAttributes: new { @class = "control-label col-md-2" })
In stock quantity

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateRole.cshtml
> +    ViewBag.Title = "Role creating";
Create role

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateRole.cshtml
> +<h2>Role creating</h2>
The same

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateStatusProduct.cshtml
> +    ViewBag.Title = "Product status creating";
Create status product

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateStatusProduct.cshtml
> +<h2>Product status creating</h2>
The same

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateStatusOrder.cshtml
> +    ViewBag.Title = "Status order creating";
Create status order

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateStatusOrder.cshtml
> +<h2>Status order creating</h2>
The same

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateTypeDelivery.cshtml
> +    ViewBag.Title = "Type delivery creating";
Create type delivery

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/CreateTypeDelivery.cshtml
> +<h2>Type delivery creating</h2>
The same

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/DeleteCategory.cshtml
> +    ViewBag.Title = "Category deleting";
Delete category

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/DeleteCategory.cshtml
> +<h1>Are you sure you want to delete category: <b>@Model.CategoryName</b>?</h1>
Do you want to delete this category: ....

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/DeleteManufacturer.cshtml
> +    ViewBag.Title = "Manufacturer deleting";
Delete manufacturer

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/DeleteManufacturer.cshtml
> +<h1>Are you sure you want to delete manufacturer: <b>@Model.ManufacturerName</b>?</h1>
Do you want to delete this.....

2022-01-13 21:40 UTC, changerd commented on CloudStore/Views/Admin/DeleteOrder.cshtml
> +<h1>Are you sure you want to delete order: <b>@Model.Id</b>?</h1>
Do you want to delete this.....

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeletePaymentMethod.cshtml
> +    ViewBag.Title = "Payment method deleting";
Delete payment method

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeletePaymentMethod.cshtml
> +<h1>Are you sure you want to delete payment method: <b>@Model.PaymentMethodName</b>?</h1>
Do you want to delete.....

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeletePaymentMethod.cshtml
> +        <a class="btn btn-outline-primary" href="@Url.Action("GetPaymentMethod", "Admin")">Back</a>
Why do you use **btn-outline primary** class if  we use **btn-default** class in other delete pages?

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteProduct.cshtml
> +    ViewBag.Title = "Product deleting";
Delete product

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteProduct.cshtml
> +<h1>Are you sure you want to delete product: <b>@Model.ProductName</b>?</h1>
Do you want to delete.........

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteRole.cshtml
> +    ViewBag.Title = "Role deleting";
Delete role

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteRole.cshtml
> +<h1>Are you sure you want to delete role: <b>@Model.Name</b>?</h1>
Do you want to delete this.....

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteStatusOrder.cshtml
> +    ViewBag.Title = "Status order deleting";
Delete status order

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteStatusOrder.cshtml
> +<h1>Are you sure you want to delete status order: <b>@Model.StatusOrderName</b>?</h1>
Do you want to delete this...

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteStatusProduct.cshtml
> +    ViewBag.Title = "Status product deleting";
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteStatusProduct.cshtml
> +<h1>Are you sure you want to delete status product: <b>@Model.StatusProductName</b>?</h1>
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteTypeDelivery.cshtml
> +    ViewBag.Title = "Type delivery deleting";
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteTypeDelivery.cshtml
> +<h1>Are you sure you want to delete delivery type: <b>@Model.TypeDeliveryName</b>?</h1>
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteUser.cshtml
> +    ViewBag.Title = "User deleting";
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/DeleteUser.cshtml
> +<h1>Are you sure you want to delete user: <b>@Model.UserName</b>?</h1>
Same comment for delete pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditCategory.cshtml
> +    ViewBag.Title = "Category edit";
Edit category

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditCategory.cshtml
> +<h2>Category edit</h2>
Edit category

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditManufacturer.cshtml
> +    ViewBag.Title = "Manufacturer edit";
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditManufacturer.cshtml
> +<h2>Manufacturer edit</h2>
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditOrder.cshtml
> +    ViewBag.Title = "Order edit № " + Model.Id;
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditOrder.cshtml
> +<h2>Oreder editing № @Model.Id</h2>
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditOrder.cshtml
> +            @Html.DisplayFor(model => model.Value) rub
Remove "rub" label or add USD sign

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditProduct.cshtml
> +    ViewBag.Title = "Product editing";
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditProduct.cshtml
> +<h2>Product editing</h2>
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditProduct.cshtml
> +            @Html.Label("In stock count", htmlAttributes: new { @class = "control-label col-md-2" })
In stock quantity

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditRole.cshtml
> +    ViewBag.Title = "Role editing";
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/EditRole.cshtml
> +<h2>Role editing</h2>
Same comment for edit pages

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetManufacturer.cshtml
> +    ViewBag.Title = "Manufacturer";
Manufacturers

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetManufacturer.cshtml
> +<h2>Manufacturer</h2>
The same

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetPaymentMethod.cshtml
> +    ViewBag.Title = "Payment method";
Payment methods

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetPaymentMethod.cshtml
> +<h2>Payment methods</h2>
The same

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetStatusOrder.cshtml
> +    ViewBag.Title = "Order status";
Order statuses

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetStatusOrder.cshtml
> +<h2>Order status</h2>
The same

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetStatusProduct.cshtml
> +    ViewBag.Title = "Product statuses";
Product statuses

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GetStatusProduct.cshtml
> +<h2>Product status</h2>
The same

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GiveRole.cshtml
> +                    <td>Add in role</td>
Add to role

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GiveRole.cshtml
> +        <div class="panel-heading">Delete to role <b>@Model.Role.Name</b></div>
Delete from role

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GiveRole.cshtml
> +                    <td colspan="2">Zero users in role</td>
Users doesn't have this role

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/Index.cshtml
> +            <div class="card-header">Data about products</div>
Products data

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/Index.cshtml
> +            <div class="card-header">Data about orders</div>
Orders data

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/Index.cshtml
> +            <div class="card-header">Data about users</div>
Users data

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Admin/Index.cshtml
> +            <div class="card-header">Data about delivery</div>
Delivery data

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Checkout.cshtml
> +                @ViewBag.Value rub
Remove "rub" or replace to USD sign

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Checkout.cshtml
> +            @Html.Label("Value", htmlAttributes: new { @class = "control-label col-md-2" })
Total

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Completed.cshtml
> +<p>Details and order status can be found in<a href="@Url.Action("Index", "Manage")"</a>profile.</p>
Details and order status you can be found in

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Index.cshtml
> +<h4>Your cart is currently empty, add the product to your cart to place an order</h4>
Your cart is empty. Add the some products to create order.

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Index.cshtml
> +                <th>Amount</th>
Quantity

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Index.cshtml
> +                    <td class="text-right">@item.Product.Cost.ToString("# rub")</td>
Remove "rub" or replace to USD sign

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Index.cshtml
> +                    @Model.Lines.Sum(s => s.Product.Cost * s.Quantity).ToString("# rub")
Remove "rub" or replace to USD sign

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/DetailsItem.cshtml
> +    ViewBag.Title = "Product creating";
Wrong title

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/DetailsItem.cshtml
> +        @if (Model.StatusProduct.StatusProductName == "Not available" || Model.StatusProduct.StatusProductName == "Out of production")
Replace "Not available" to "Out of stock"

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/DetailsItem.cshtml
> +                <button class="btn btn-default disabled btn-lg btn-block">Add to Shopping Cart</button>
Add to Cart

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/DetailsItem.cshtml
> +                    <input type="submit" class="btn btn-default btn-lg btn-block" value="Notify me when a product is in stock" />
Notify me when a product will in stock

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/DetailsItem.cshtml
> +                    <label for="inputquantity">Amount</label>
Quantity

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/Items.cshtml
> +                    <span class="pull-right label label-default">@item.Cost.ToString("# rub")</span>
The same comment for Rubles currency

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Catalog/SearchResult.cshtml
> +            <span class="pull-right label label-default">@item.Cost.ToString("# rub")</span>
The same comment for quantity

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Home/About.cshtml
> +    ViewBag.Title = "About shop";
About

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Home/Index.cshtml
>  ﻿
Delete unused code from this file

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Manage/Edit.cshtml
> +    ViewBag.Title = "Profile edit";
Edit profile

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Manage/Edit.cshtml
> +<h2>Profile edit</h2>
Edit profile

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Shared/_Layout.cshtml
> +                        @Html.ActionLink("Catalog", "Index", "Catalog", new { @class = "nav-link", @href = "/Catalog" })
Why do you use object "href" if we use Razor operator for links?

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Views/Shared/_LoginPartial.cshtml
> +                @Html.ActionLink("Hello, " + User.Identity.GetUserName() + "!", "Index", "Manage", new { @class = "nav-link", @href = "/Manage/Index" })
Same comment for "href" object

2022-01-13 21:40 UTC, cxxxxxxd commented on CloudStore/Web.config
> +		<add name="StoreContext" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename='|DataDirectory|\CloudStore.mdf';Integrated Security=True;MultipleActiveResultSets=True" providerName=
Undo changes

2022-01-13 21:45 UTC, changerd commented
Remove style class **btn-default** and replace all default buttons to **btn-dark**.
Why we will need add old bootstrap button styles if we already use latest version? Use existing styles in this case.

2022-01-14 16:31 UTC, cxxxxxxd requested changes

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Models/Line.cs
> +        [Display(Name = "Count")]
Quantity

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Models/TypeDelivery.cs
> +        [Display(Name = "Pick up")]
What?

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Models/StoreContext.cs
> +            StatusProduct sp2 = new StatusProduct { StatusProductName = "Not in stock" };
Out of stock

2022-01-14 16:31 UTC, changerd commented on CloudStore/Views/Admin/EditOrder.cshtml
> +    ViewBag.Title = "Order edit № " + Model.Id;
?

2022-01-14 16:31 UTC, changerd commented on CloudStore/Views/Admin/EditProduct.cshtml
> +            @Html.Label("In stock count", htmlAttributes: new { @class = "control-label col-md-2" })
???

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Views/Admin/GiveRole.cshtml
> +                    <td colspan="2">Users doesn't have this role</td>
Replace doesn't to don't

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Views/Cart/Completed.cshtml
> +<p>Details and order status can be found in<a href="@Url.Action("Index", "Manage")"</a>.</p>
wrong <a> tag, fix this and put "profile" to this tag

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Models/StoreContext.cs
> +            TypeDelivery td1 = new TypeDelivery { TypeDeliveryName = "Pickup" };
?

2022-01-14 16:31 UTC, cxxxxxxd commented on CloudStore/Views/Shared/_Layout.cshtml
> +                        @Html.ActionLink("Catalog", "Index", "Catalog", new { @class = "nav-link", @href = "/Catalog" })
Ask to the question

2022-01-14 16:31 UTC, changerd commented on CloudStore/Views/Shared/_LoginPartial.cshtml
> +                @Html.ActionLink("Hello, " + User.Identity.GetUserName() + "!", "Index", "Manage", new { @class = "nav-link", @href = "/Manage/Index" })
Ask to the question

2022-01-14 17:26 UTC, syegod commented on CloudStore/Models/TypeDelivery.cs
> +        [Display(Name = "Pick up")]
you told me to do it

2022-01-14 17:52 UTC, syegod commented
aboba

2022-01-14 22:20 UTC, cxxxxxxd approved these changes

2022-01-14 22:20 UTC, merged